"""empty message

Revision ID: 83db18c2faa6
Revises: 
Create Date: 2019-10-05 13:58:11.057942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83db18c2faa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
